import{i as m,S as u}from"./assets/vendor-7659544d.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const d="42576318-0e1c04293cd098153cdda1833",f="https://pixabay.com/api/";document.querySelector(".loader");function p(s){const e=new URLSearchParams({key:d,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),a=document.querySelector(".loader");return a.style.display="block",fetch(`${f}?${e}`).then(o=>{if(!o.ok)throw new Error("Network response was not OK!");return o.json()}).then(o=>(a.style.display="none",o.hits.length===0&&m.error({fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),o)).catch(o=>console.error("Error fetching data:",o))}function g(s){return s.hits.map(e=>`<div class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
            <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
        </a>
        <div class="gallery-image-info">
            <p class="image-info-item"><span class="image-items-text">Likes: </span>${e.likes}</p>
            <p class="image-info-item"><span class="image-items-text">Views: </span>${e.views}</p>
            <p class="image-info-item"><span class="image-items-text">Comments: </span>${e.comments}</p>
            <p class="image-info-item"><span class="image-items-text">Downloads: </span>${e.downloads}</p>
        </div>
    </div>`).join("")}const h=new u(".gallery-link",{captionsData:"alt",captionDelay:250}),l=document.querySelector("#searchForm"),n=document.querySelector(".gallery");let c="";l.addEventListener("submit",y);function y(s){s.preventDefault(),n.innerHTML="",c=l.elements.searchQuery.value.trim(),p(c).then(e=>{const a=g(e);n.insertAdjacentHTML("beforeend",a),h.refresh()}).catch(e=>console.error("Error fetching data:",e))}
//# sourceMappingURL=commonHelpers.js.map
